### ISSUE TITLE
Reflect property to attribute example is outdated

### ISSUE THREAD

**Issue by janlat** [LarsDenBakker/lit-html-examples#14]
LitElement now supports property option called `reflect`, so instead of this whole method:

https://github.com/LarsDenBakker/lit-html-examples/blob/d4460dbcd19165770924fdf80f2b6d3cd772f049/src/2-intermediate/12-reflect-property-to-attribute.js#L24-L56

you could just set properties like so:
```js
{ 
  count: { type: Number, reflect: true }
  message: { type: String }, 
}
```
I'd make a PR, but I'm not sure if this example is even needed anymore.

**Comment by LarsDenBakker** [comment]
You're right, please look here: https://open-wc.org/developing/ for up to date examples.
