### ISSUE TITLE
Add upwards data flow example

### ISSUE THREAD

**Issue by LarsDenBakker** [LarsDenBakker/lit-html-examples#5]

**Comment by motss** [comment]
@LarsDenBakker What is upwards data flow? Is it something like in Polymer to notify changed properties?

**Comment by LarsDenBakker** [comment]
@motss Yes, how to notify parent elements of changes. I don't think two way binding should be encouraged, but one way upwards can be useful sometimes.

**Comment by motss** [comment]
@LarsDenBakker I see. I would say

```
...
this.dispatchEvent(new CustomEvent('some-changed', {
  detail: { changed: 'haha' },
  composed: true,
  bubbles: true,
}));
...
```
is the way to go for upwards data flow if I understand correctly.

**Comment by LarsDenBakker** [comment]
Agreed

**Comment by morbidick** [comment]
Hi,
just migrated one of my elements to npm and Lit, thx @LarsDenBakker for this example collection, helped a lot as quick reference!
About dispatching events for two way databinding with Polymer i used:
```javascript
this.dispatchEvent(new CustomEvent('some-changed', {
  detail: { value: 'new-value' }, //having the value always "in the same place" makes binding code easier
  composed: true,
  bubbles: false, //the event doesnt need to bubble all the way up to the document, binding in parent scope is enough
}));
```

**Comment by motss** [comment]
@morbidick `bubbles` is in fact optional.
